repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: end-of-file-fixer
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: shellformat
        name: Format '*.sh' files
        entry: /home/vscode/.local/bin/shfmt
        language: system
        files: ^(.*)\.sh$
        args: [-i, "2", -w]
